Runners/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Runners.Models;

namespace Runners.Controllers
{
    public class ReportsController : Controller
    {
        private readonly AthleticsContext _context;

        public ReportsController(AthleticsContext context)
        {
            _context = context;
        }

        // GET: Reports
        public async Task<IActionResult> Index()
        {
              return View(await _context.Runners.ToListAsync());
        }

        // GET: Reports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (runner == null)
            {
                return NotFound();
            }

            return View(runner);
        }

        // GET: Reports/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,Name,Minutes,Seconds")] Runner runner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(runner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(runner);
        }

        // GET: Reports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners.FindAsync(id);
            if (runner == null)
            {
                return NotFound();
            }
            return View(runner);
        }

        // POST: Reports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Name,Minutes,Seconds")] Runner runner)
        {
            if (id != runner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(runner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RunnerExists(runner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(runner);
        }

        // GET: Reports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (runner == null)
            {
                return NotFound();
            }

            return View(runner);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Runners == null)
            {
                return Problem("Entity set 'AthleticsContext.Runners'  is null.");
            }
            var runner = await _context.Runners.FindAsync(id);
            if (runner != null)
            {
                _context.Runners.Remove(runner);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RunnerExists(int id)
        {
          return _context.Runners.Any(e => e.Id == id);
        }
    }
}

Runners/Controllers/RunnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Runners.Models;

namespace Runners.Controllers
{
    public class RunnersController : Controller
    {
        private readonly AthleticsContext _context;

        public RunnersController(AthleticsContext context)
        {
            _context = context;
        }

        // GET: Runners
        public async Task<IActionResult> Index()
        {
              return View(await _context.Runners.ToListAsync());
        }

        // GET: Runners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (runner == null)
            {
                return NotFound();
            }

            return View(runner);
        }

        // GET: Runners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Runners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Number,Name,Minutes,Seconds")] Runner runner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(runner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(runner);
        }

        // GET: Runners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners.FindAsync(id);
            if (runner == null)
            {
                return NotFound();
            }
            return View(runner);
        }

        // POST: Runners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Number,Name,Minutes,Seconds")] Runner runner)
        {
            if (id != runner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(runner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RunnerExists(runner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(runner);
        }

        // GET: Runners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Runners == null)
            {
                return NotFound();
            }

            var runner = await _context.Runners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (runner == null)
            {
                return NotFound();
            }

            return View(runner);
        }

        // POST: Runners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Runners == null)
            {
                return Problem("Entity set 'AthleticsContext.Runners'  is null.");
            }
            var runner = await _context.Runners.FindAsync(id);
            if (runner != null)
            {
                _context.Runners.Remove(runner);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RunnerExists(int id)
        {
          return _context.Runners.Any(e => e.Id == id);
        }
    }
}

Runners/Views/Reports/Index.cshtml
@model IEnumerable<Runners.Models.Runner>

@{
    ViewData["Title"] = "Index";
    int data = 0;
}
@foreach (var item in Model){
    data++;
}

@if (data>0){
<h1>Reporte de velocidad</h1>

<p>+++++++++++++++++++++++++++++++++++++++++++++++</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Corredor
            </th>
            <th>
              Tiempo(minutos, segundos)
            </th>
            <th>
               m/s
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            double velocidad = Math.Round(2000 / ((item.Minutes * 60) + item.Seconds), 2);

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Minutes):@Html.DisplayFor(modelItem => item.Seconds)
                </td>
                <td>
                    @velocidad
                </td>
            </tr>
        }
    </tbody>
</table>
<table class="table">
    <thead>
        <tr>
            <th>
              Mejor velocidad
            </th>
            <th>
                Peor velocidad
            </th>
            <th>
                Velocidad promedio
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            double lessRapid = 0;
            double mostRapid = 0;
            double average = 0;
            List<double> runners = new List<double>();
                @foreach (var item in Model)
        {
            double velocidad = Math.Round(2000 / ((item.Minutes * 60) + item.Seconds), 2);
            runners.Add(velocidad);
            average += velocidad;
            }
            runners.Sort();
            lessRapid = runners.LastOrDefault();
            mostRapid = runners.FirstOrDefault();
            average = Math.Round(average / runners.Count);
        }

        <tr>
                <td>
                @lessRapid m/s
                </td>
                <td>
                @mostRapid m/s
                </td>
                <td>
                @average m/s
                </td>
            </tr>
     
    </tbody>
</table>
}else{
    <div class="col-12 mb-3">

        <div class="toast align-items-center text-white bg-danger border-0 show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
                <div class="toast-body">
                    Debe de ingresar primeramente un corredor para poder ver los reportes
                    
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 mb-3">

        <a class="btn btn-primary btn-block" asp-area="" asp-controller="Runners" asp-action="index">Ir a registrar un corredor</a>

    </div>
}